### ISSUE TITLE
PHP tags

### ISSUE THREAD

**Issue by JuneSites** [BraisC/Kinda-Monokai-Dark#1]
I love this theme! Thank you so much. I do have a question about the PHP tags. You have them set to orange and bold (which is perfect), but any PHP tags that are within javascript tags don't get the special styling. I have tried so many different "scope" variables but can't seem to make it work. Is there a way to set the styling for ALL php opening and closing tags regardless of where they are located? Thanks for your help.

**Comment by BraisC** [comment]
I am looking into it and it looks like PHP tags only are recognized inside HTML, so I don't think it is possible :(
If you find a way, I would be very happy to implement it, but I tested other themes and it looks like no one could do it.

Thanks for your message.
